import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  userSidebar: [
    "intro",
    {
      type: "category",
      label: "User Guide",
      collapsed: false,
      items: [
        "user-guide/getting-started",
        "user-guide/dashboard",
        "user-guide/preop-form",
        "user-guide/intraop-form",
        "user-guide/postop-form",
        "user-guide/printing",
        "user-guide/handover",
        "user-guide/settings",
      ],
    },
    "admin-guide",
    "offline-mode",
    "pediatric-mode",
    "clinical-rules",
    "pediatric-platform-draft",
    "self-hosting",
    "release-v7",
    "architecture",
    "api",
    "autosave-manager",
    "data-research",
    "research-browser",
    {
      type: "category",
      label: "Hospital Appliance",
      collapsed: true,
      items: [
        "appliance/quick-start",
        "appliance/host-preparation",
        "appliance/installation",
        "appliance/operations",
        "appliance/updates-compatibility",
        "appliance/backup-restore",
        "appliance/security",
        "appliance/network-boundaries",
        "appliance/account-provisioning",
        "appliance/status-monitor",
        "appliance/host-observability",
        "appliance/terminology-import",
        "appliance/research-control",
        "appliance/central-enrollment",
        "appliance/central-status-control",
        "appliance/external-ai-control",
        "appliance/clinical-guidance-policy",
        "appliance/preoperative-profile",
        "appliance/audit-evidence",
        "appliance/secret-rotation",
        "appliance/release-validation",
        "appliance/open-security-decisions",
        "appliance/architecture",
      ],
    },
    "changelog",
  ],
}

export default sidebars
